openapi: 3.0.0
info:
  title: Bonus Program API
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Authenticate and get JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Token generated
        "401":
          description: Invalid credentials
  /users/bonus:
    get:
      summary: Get user's bonus information
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Bonus data retrieved
        "401":
          description: Unauthorized
  /users/transactions:
    post:
      summary: Add a transaction
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  format: float
      responses:
        "200":
          description: Transaction added
